# Generated by Django 5.2.5 on 2025-08-31 12:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcentratorOreFactory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Бүртгэсэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Зассан огноо')),
                ('shift', models.IntegerField(blank=True, choices=[(100, 'Өдөр'), (200, 'Шөнө')], null=True)),
                ('operation_date', models.DateField(blank=True, null=True)),
                ('entry_type', models.IntegerField(choices=[(100, 'Төлөвлөгөө'), (200, 'Гүйцэтгэл')], default=200)),
                ('concentrator_type', models.IntegerField(choices=[(100, 'БҮ-1'), (200, 'БҮ-2')], null=True)),
                ('line_type', models.IntegerField(blank=True, choices=[(100, 'Шугам 1'), (200, 'Шугам 2')], null=True)),
                ('block_number', models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Зөвхөн том үсэг, тоо, болон (:) тэмдэгт ашиглана уу.', regex='^([A-ZА-Я0-9]+)(:[A-ZА-Я0-9]+)*$')])),
                ('mixed_ratio', models.CharField(null=True, validators=[django.core.validators.RegexValidator(message='Зөвхөн тоо болон (:) тэмдэгт ашиглана уу.', regex='^[0-9:]+$')])),
                ('auto_pu_total_ore', models.FloatField(null=True)),
                ('off_to_dump_ore', models.FloatField(null=True)),
                ('field_remaining', models.FloatField(blank=True, null=True)),
                ('ore_moisture', models.FloatField(null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Бүртгэсэн')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Зассан')),
            ],
            options={
                'verbose_name': 'Үйлдвэр тэжээсэн хүдэр',
                'db_table': 'fc_concentrator_ore_factories',
                'permissions': [('view_concentrator_dashboard', 'Can view concentrator dashboard')],
            },
        ),
    ]
