# Generated by Django 5.2.5 on 2025-08-31 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserShift',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('shift', models.IntegerField(choices=[(100, 'Өдөр'), (200, 'Шөнө')], null=True)),
                ('operation_date', models.DateTimeField(null=True)),
                ('flotation_type', models.IntegerField(choices=[(100, '1 дүгээр шугам'), (200, '2 дүгээр шугам')], null=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'user_shifts',
            },
        ),
    ]
